name: 'Test Environment Variable Stuff'

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'Development'

jobs:
    print-variable:
      runs-on: ubuntu-latest
      environment: '${{ github.event.inputs.environment }}'
    
      steps:
        - name: Print Var
          run: echo ${{ vars.GCP_PROJECT_NAME }}

        - name: RegEx Testing
          run: |
            echo ${{ vars.ARTEFACT_REGISTRY_ROOT }}
            artifact_registry = 'wibble.com/this/that'
            echo $artifact_registry
            artifact_registry_hostname=$(echo $artifact_registry | grep -o '^([^\/]+)')
            echo $artifact_registry_hostname