name: 'Test Environment Variable Stuff'

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'Development'

jobs:
    print-variable:
      runs-on: ubuntu-latest
      environment: '${{ github.event.inputs.environment }}'
    
      steps:
        - name: Print Var
          run: echo ${{ vars.GCP_PROJECT_NAME }}

        - name: RegEx Testing
          run: |
            roothostname=$(echo "${{ vars.ARTEFACT_REGISTRY_ROOT }}" | grep -o '^([^\/]+)')
            echo $roothostname